name: Build and Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: NuGet Packages
          path: artifacts/pkgs
          merge-multiple: true

      - name: Download Documentation Artifacts
        uses: actions/download-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: Documentation Artifacts
          path: artifacts/docs

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Setup dev environment
        shell: &dev-shell 'nix develop -c bash -eo pipefail {0}'
        run: 'true'

      - name: Publish Packages
        shell: *dev-shell
        env:
          KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push artifacts/pkgs/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push artifacts/pkgs/*.snupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Deploy Documentation
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: artifacts/docs
          strip_components: 2
          target: ~/NetCord/html
